#!/usr/bin/env python

import sys
import argparse
import logging

import new
import info

def init_logger():
    logger = logging.getLogger(__name__)

    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(ch)

    logger.setLevel(logging.INFO)

    return logger

def make_parser():
    parser = argparse.ArgumentParser()

    subparsers = parser.add_subparsers()

    new.make_subparser(subparsers)
    info.make_subparser(subparsers)

    return parser

def main(args):
    args = make_parser().parse_args(args)
    args.logger = init_logger()
    try:
        args.func(args)
    except new.DirectoryExists as e:
        args.logger.error(e)
    except new.MissingTemplate as e:
        args.logger.error(e)
    except new.TemplateParseError as e:
        args.logger.error(e)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
